### ISSUE TITLE
PlayerDropItemEvent - IllegalArgumentException: Cannot drop air

### ISSUE THREAD

**Issue by baxandrei** [ServerSelectorX/ServerSelectorX#160]
```
[02:50:43 ERROR]: Could not pass event PlayerDropItemEvent to ServerSelectorX vPremium-2.0.0
java.lang.IllegalArgumentException: Cannot drop air
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.15.2.jar:git-Paper-71]
        at net.minecraft.server.v1_15_R1.EntityItem.setItemStack(EntityItem.java:433) ~[patched_1.15.2.jar:git-Paper-71]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftItem.setItemStack(CraftItem.java:35) ~[patched_1.15.2.jar:git-Paper-71]
        at xyz.derkades.serverselectorx.ItemMoveDropCancelListener$1.onDrop(ItemMoveDropCancelListener.java:23) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-71]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-71]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-71]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.2.jar:git-Paper-71]
        at net.minecraft.server.v1_15_R1.EntityHuman.a(EntityHuman.java:607) ~[patched_1.15.2.jar:git-Paper-71]
        at net.minecraft.server.v1_15_R1.EntityPlayer.a(EntityPlayer.java:1797) ~[patched_1.15.2.jar:git-Paper-71]
        at net.minecraft.server.v1_15_R1.EntityHuman.n(EntityHuman.java:562) ~[patched_1.15.2.jar:git-Paper-71]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1298) ~[patched_1.15.2.jar:git-Paper-71]
        at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.15.2.jar:git-Paper-71]
        at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-71]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-71]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-71]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-71]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-71]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-71]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-71]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-71]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-71]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-71]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-71]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

```

also cancel-item-drop: true in inventory.yml

**Comment by Derkades** [comment]
Thanks for reporting the bug, it is fixed in version 2.0.1 which I plan to release today
