### ISSUE TITLE
Error occurred while enabling ServerSelectorX vPremium-2.1.1 

### ISSUE THREAD

**Issue by Mrok71** [ServerSelectorX/ServerSelectorX#205]
[15:58:15] [Server thread/INFO]: [ServerSelectorX] Enabling ServerSelectorX vPremium-2.1.1
[15:58:15] [Server thread/ERROR]: Error occurred while enabling ServerSelectorX vPremium-2.1.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean me.clip.placeholderapi.PlaceholderAPI.registerExpansion(me.clip.placeholderapi.expansion.PlaceholderExpansion)'
	at xyz.derkades.serverselectorx.placeholders.PapiExpansionRegistrar.register(PapiExpansionRegistrar.java:10) ~[?:?]
	at xyz.derkades.serverselectorx.Main.onEnable(Main.java:87) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-134]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-134]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-134]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-134]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-134]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[15:58:15] [Server thread/INFO]: [ServerSelectorX] Disabling ServerSelectorX vPremium-2.1.1

**Comment by Derkades** [comment]
PlaceholderAPI 2.10.7+ is currently broken for the latest version on spigotmc.org. Please use a beta build from https://ci.derkad.es/job/ServerSelectorX%20Premium/ until I update the version on spigot

**Comment by Derkades** [comment]
This update is on spigot now
