### ISSUE TITLE
after update to 1.16.4 - Method not loaded! 'ITEMSTACK_NMSCOPY'

### ISSUE THREAD

**Issue by Mrok71** [ServerSelectorX/ServerSelectorX#214]
[17:10:30 ERROR]: Could not pass event PlayerJoinEvent to ServerSelectorX vPremium-2.1.2
xyz.derkades.serverselectorx.lib.nbtapi.NbtApiException: Method not loaded! 'ITEMSTACK_NMSCOPY'
        at xyz.derkades.serverselectorx.lib.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:154) ~[?:?]
        at xyz.derkades.serverselectorx.lib.nbtapi.NBTItem.getCompound(NBTItem.java:53) ~[?:?]
        at xyz.derkades.serverselectorx.lib.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:548) ~[?:?]
        at xyz.derkades.serverselectorx.lib.nbtapi.NBTCompound.setInteger(NBTCompound.java:135) ~[?:?]
        at xyz.derkades.serverselectorx.lib.derkutils.bukkit.ItemBuilder.hideFlags(ItemBuilder.java:193) ~[?:?]
        at xyz.derkades.serverselectorx.Main.getItemBuilderFromItemSection(Main.java:168) ~[?:?]
        at xyz.derkades.serverselectorx.ItemGiveListener.giveItems(ItemGiveListener.java:96) ~[?:?]
        at xyz.derkades.serverselectorx.ItemGiveListener.onJoin(ItemGiveListener.java:37) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor246.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-261]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:220) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:165) ~[?:git-Paper-261]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:385) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1383) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-261]
        at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by Derkades** [comment]
Please use the [latest beta](https://ci.derkad.es/job/ServerSelectorX%20Premium/lastSuccessfulBuild/artifact/target/ServerSelectorX-Premium-2.1.3-beta.jar), the version on spigot doesn't support 1.16.4 yet.
