### ISSUE TITLE
PlayerInteractEvent - Been working fine

### ISSUE THREAD

**Issue by ICEconchy** [ServerSelectorX/ServerSelectorX#226]
Hello, recently got this error in console and nothing works now. 

`[14.01 14:38:22] [Server] [ERROR] Could not pass event PlayerInteractEvent to ServerSelectorX vPremium-2.1.2-beta
[14.01 14:38:22] [Server] xyz.derkades.serverselectorx.lib.nbtapi.NbtApiExceptionMethod not loaded! 'ITEMSTACK_NMSCOPY'
[14.01 14:38:22] [Server] 	at xyz.derkades.serverselectorx.lib.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:154) ~[?:?]
[14.01 14:38:22] [Server] 	at xyz.derkades.serverselectorx.lib.nbtapi.NBTItem.getCompound(NBTItem.java:53) ~[?:?]
[14.01 14:38:22] [Server] 	at xyz.derkades.serverselectorx.lib.nbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:568) ~[?:?]
[14.01 14:38:22] [Server] 	at xyz.derkades.serverselectorx.lib.nbtapi.NBTCompound.hasKey(NBTCompound.java:512) ~[?:?]
[14.01 14:38:22] [Server] 	at xyz.derkades.serverselectorx.ItemClickListener.onInteract(ItemClickListener.java:48) ~[?:?]
[14.01 14:38:22] [Server] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor80.execute(Unknown Source) ~[?:?]
[14.01 14:38:22] [Server] 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:510) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:473) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:468) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:464) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1601) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1132) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1125) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1086) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-412]
[14.01 14:38:22] [Server] 	at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by Derkades** [comment]
Please update to a more recent version, 1.16.4 compatibility was added 2 months ago in 2.1.3
