### ISSUE TITLE
Error activating the plugin - translated by google

### ISSUE THREAD

**Issue by prgames123** [ServerSelectorX/ServerSelectorX#234]
I was recommended this plugin to use in my lobby, when I installed it in my lobby this error message appeared, the items are not being distributed.

I don't know if it's a problem with my server or the plugin

minecraft version: **1.9**

we are using **bungeecord** and using **spigot** on the servers

the commands are still sampled but I don't know if they work
![image](https://user-images.githubusercontent.com/53787493/107393196-47cd0c80-6ad9-11eb-8525-042a077a41d2.png)

```
[15:56:59 INFO]: [ServerSelectorX] Enabling ServerSelectorX vPremium-2.1.5-beta-legacy
[15:56:59 ERROR]: Error occurred while enabling ServerSelectorX vPremium-2.1.5-beta-legacy (Is it up to date?)
java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
at org.bstats.MetricsBase.checkRelocation(MetricsBase.java:220) ~[?:?]
at org.bstats.MetricsBase.<init>(MetricsBase.java:104) ~[?:?]
at xyz.derkades.serverselectorx.lib.bstats.Metrics.<init>(Metrics.java:73) ~[?:?]
at xyz.derkades.serverselectorx.Stats.<init>(Stats.java:16) ~[?:?]
at xyz.derkades.serverselectorx.Main.onEnable(Main.java:87) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[server.jar:git-Spigot-d20369f-7fc5cd8]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-d20369f-7fc5cd8]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-d20369f-7fc5cd8]
at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [server.jar:git-Spigot-d20369f-7fc5cd8]
at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [server.jar:git-Spigot-d20369f-7fc5cd8]
at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [server.jar:git-Spigot-d20369f-7fc5cd8]
at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [server.jar:git-Spigot-d20369f-7fc5cd8]
at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [server.jar:git-Spigot-d20369f-7fc5cd8]
at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [server.jar:git-Spigot-d20369f-7fc5cd8]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [server.jar:git-Spigot-d20369f-7fc5cd8]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```

if you need any more information I am available

**thanks in advance**

**Comment by Derkades** [comment]
fixed
