### ISSUE TITLE
error on pterodactyl

### ISSUE THREAD

**Issue by Matthew-MBG** [ServerSelectorX/ServerSelectorX#244]
`[17:41:06 ERROR]: Could not pass event PlayerInteractEvent to ServerSelectorX v3.6.0
java.lang.NullPointerException: null
        at xyz.derkades.serverselectorx.lib.derkutils.bukkit.ItemBuilder.name(ItemBuilder.java:55) ~[?:?]
        at xyz.derkades.serverselectorx.SelectorMenu.<init>(SelectorMenu.java:127) ~[?:?]
        at xyz.derkades.serverselectorx.SelectorOpenListener.onInteract(SelectorOpenListener.java:51) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor72.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-703]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-703]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-703]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-703]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[patched_1.16.5.jar:git-Paper-703]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:509) ~[patched_1.16.5.jar:git-Paper-703]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:504) ~[patched_1.16.5.jar:git-Paper-703]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:500) ~[patched_1.16.5.jar:git-Paper-703]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1757) ~[patched_1.16.5.jar:git-Paper-703]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:32) ~[patched_1.16.5.jar:git-Paper-703]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:9) ~[patched_1.16.5.jar:git-Paper-703]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-703]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-703]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-703]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-703]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-703]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1263) ~[patched_1.16.5.jar:git-Paper-703]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1256) ~[patched_1.16.5.jar:git-Paper-703]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-703]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1217) ~[patched_1.16.5.jar:git-Paper-703]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1131) ~[patched_1.16.5.jar:git-Paper-703]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-703]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by PythonGaming** [comment]
What version is your server, and did you use PlayerSelectorX or PlayerSelectorX-legacy

**Comment by Derkades** [comment]
Can you try the latest beta version: https://ci.derkad.es/view/ServerSelectorX/
