### ISSUE TITLE
Plugin not starting

### ISSUE THREAD

**Issue by FairInHeight** [ServerSelectorX/ServerSelectorX#254]
I am on the newest version of paper and every plugin on my list except serverselectorx will load. 

org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=xyz/derkades/serverselectorx/Main, offset=6
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.16.5.jar:git-Paper-778]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Paper-778]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Paper-778]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-778]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-778]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-778]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-778]
at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3056.00000000DDEC4530.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Thread.java:819) [?:1.8.0_232]
Caused by: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=xyz/derkades/serverselectorx/Main, offset=6
at java.lang.ClassLoader.defineClassImpl(Native Method) ~[?:1.8.0_232]
at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:397) ~[?:1.8.0_232]
at java.lang.ClassLoader.defineClass(ClassLoader.java:358) ~[?:1.8.0_232]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_232]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:201) ~[patched_1.16.5.jar:git-Paper-778]
at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:952) ~[?:1.8.0_232]
at java.lang.ClassLoader.loadClass(ClassLoader.java:897) ~[?:1.8.0_232]
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-778]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-778]
at java.lang.ClassLoader.loadClass(ClassLoader.java:880) ~[?:1.8.0_232]
at java.lang.Class.forNameImpl(Native Method) ~[?:1.8.0_232]
at java.lang.Class.forName(Class.java:403) ~[?:1.8.0_232]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.16.5.jar:git-Paper-778]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Paper-778]
... 8 more

**Comment by FairInHeight** [comment]
im stupid was using java 8
