### ISSUE TITLE
CraftOfflinePlayer cannot be cast to class org.bukkit.entity.Player

### ISSUE THREAD

**Issue by marcopaggioro** [ServerSelectorX/ServerSelectorX#280]
```
[10:37:03 INFO]: [+] ritter
[10:37:03 INFO]: [AuthMe] ritter logged in CENSORED
[10:37:03 INFO]: [FastLogin] No on-going login session for player: CraftPlayer{name=ritter} with ID CENSORED:33101
[10:37:48 WARN]: ritter was kicked due to keepalive timeout!
[10:37:48 INFO]: ritter lost connection: Timed out
[10:37:48 INFO]: [-] ritter
[10:37:48 WARN]: [ServerSelectorX] Task #887890 for ServerSelectorX v3.6.2 generated an exception
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.CraftOfflinePlayer cannot be cast to class org.bukkit.entity.Player (org.bukkit.craftbukkit.v1_17_R1.CraftOfflinePlayer and org.bukkit.entity.Player are in unnamed module of loader 'app')
        at xyz.derkades.serverselectorx.lib.derkutils.bukkit.menu.MenuCloseEvent.getPlayer(MenuCloseEvent.java:26) ~[ServerSelectorX-3.6.2.jar:?]
        at xyz.derkades.serverselectorx.SelectorMenu.onClose(SelectorMenu.java:200) ~[ServerSelectorX-3.6.2.jar:?]
        at xyz.derkades.serverselectorx.lib.derkutils.bukkit.menu.IconMenu$1.run(IconMenu.java:77) ~[ServerSelectorX-3.6.2.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Airplane-103]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Airplane-103]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1564) ~[patched_1.17.1.jar:git-Airplane-103]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Airplane-103]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Airplane-103]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1279) ~[patched_1.17.1.jar:git-Airplane-103]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-103]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

```

**The error was printed in a loop until the same player returned to the server (2 hours later!)**

**Comment by Derkades** [comment]
Please update to 3.6.3
