### ISSUE TITLE
Not working in 1.21.4

### ISSUE THREAD

**Issue by Stoupy51** [ServerSelectorX/ServerSelectorX#398]
As title says

**Comment by Stoupy51** [comment]
When logging:
```hs
[23:06:39 ERROR]: Could not pass event PlayerJoinEvent to ServerSelectorX vPremium-3.1.6-beta
java.lang.ExceptionInInitializerError: null
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.lib.nbtapi.NBTCompound.getStringList(NBTCompound.java:816) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.lib.nbtapi.NBTCompound.getStringList(NBTCompound.java:33) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.conditional.ConditionalItem.lambda$getItem$2(ConditionalItem.java:192) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.lib.nbtapi.NBT.modify(NBT.java:252) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.lib.derkutils.bukkit.NbtItemBuilder.editNbt(NbtItemBuilder.java:100) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.conditional.ConditionalItem.lambda$getItem$3(ConditionalItem.java:191) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.Main.getItemBuilderFromMaterialString(Main.java:187) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.conditional.ConditionalItem.getItem(ConditionalItem.java:101) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.HotbarItemManager.giveItem(HotbarItemManager.java:86) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.HotbarItemManager.updateSsxItems(HotbarItemManager.java:184) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.HotbarItemManager$BukkitEventListener.onJoin(HotbarItemManager.java:201) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:350) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1579) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1556) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1549) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:117) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1699) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1331) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:341) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "pk" is null
	at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328) ~[?:?]
	at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242) ~[?:?]
	at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097) ~[?:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:79) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.3.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.lib.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:59) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	... 35 more
```

**Comment by Stoupy51** [comment]
When right clicking with the menu item:
```hs
[23:08:59 ERROR]: Could not pass event PlayerInteractEvent to ServerSelectorX vPremium-3.1.6-beta
java.lang.NoClassDefFoundError: Could not initialize class xyz.derkades.serverselectorx.lib.nbtapi.NBTReflectionUtil
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.lib.nbtapi.NBTCompound.hasTag(NBTCompound.java:720) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.ItemClickListener.onInteract(ItemClickListener.java:58) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:603) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:559) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:554) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:550) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2087) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:47) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:10) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1579) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1556) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1549) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1500) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1346) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:341) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
	at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328) ~[?:?]
	at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242) ~[?:?]
	at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097) ~[?:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:79) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.3.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.lib.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:59) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.lib.nbtapi.NBTCompound.getStringList(NBTCompound.java:816) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.lib.nbtapi.NBTCompound.getStringList(NBTCompound.java:33) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.conditional.ConditionalItem.lambda$getItem$2(ConditionalItem.java:192) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.lib.nbtapi.NBT.modify(NBT.java:252) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.lib.derkutils.bukkit.NbtItemBuilder.editNbt(NbtItemBuilder.java:100) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.conditional.ConditionalItem.lambda$getItem$3(ConditionalItem.java:191) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.Main.getItemBuilderFromMaterialString(Main.java:187) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.conditional.ConditionalItem.getItem(ConditionalItem.java:101) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.HotbarItemManager.giveItem(HotbarItemManager.java:86) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.HotbarItemManager.updateSsxItems(HotbarItemManager.java:184) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at ServerSelectorX-Premium-3.1.6-beta.jar/xyz.derkades.serverselectorx.HotbarItemManager$BukkitEventListener.onJoin(HotbarItemManager.java:201) ~[ServerSelectorX-Premium-3.1.6-beta.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:350) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1579) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1556) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1549) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:117) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1699) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1331) ~[paper-1.21.4.jar:1.21.4-13-4803421]
	... 2 more
```

**Comment by Derkades** [comment]
Huh, that is unexpected. I will take a look soon.

**Comment by Derkades** [comment]
Now fixed in the latest beta version. Thanks for reporting
