### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Slimerblue22** [ServerSelectorX/ServerSelectorX#56]
[ServerSelectorX] Plugin ServerSelectorX v3.2.4 generated an exception while executing task 94
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.WOODEN_                                                                                        SWORD
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_151]
        at org.bukkit.Material.valueOf(Material.java:1) ~[spigot-1.12.1.jar:git-                                                                                        Spigot-da42974-8f47214]
        at xyz.derkades.serverselectorx.SelectorMenu$1.run(SelectorMenu.java:200                                                                                        ) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.jav                                                                                        a:71) ~[spigot-1.12.1.jar:git-Spigot-da42974-8f47214]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsy                                                                                        ncTask.java:52) [spigot-1.12.1.jar:git-Spigot-da42974-8f47214]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                                                                        java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                                                                        .java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
![image](https://user-images.githubusercontent.com/29098956/33221448-9eed3034-d11d-11e7-954c-f34069584a1a.png)
**If you need more details let me know**

**Comment by Derkades** [comment]
Use WOOD_SWORD for the item name instead of WOODEN_SWORD. This is wrong by default, sorry for the confusion. Will be fixed in the next version.
