### ISSUE TITLE
Not sure what I'm doing wrong..

### ISSUE THREAD

**Issue by adracamas** [ServerSelectorX/ServerSelectorX#80]
It looks like it WANTS to work.. but is throwing errors on me.
`

[01:01:33] [Server thread/WARN]: [ServerSelectorX] A sound with the name HORSE_ARMOR could not be found. Make sure that it is the right name for your server version.
--
[01:01:33] [Craft Scheduler Thread - 8/WARN]: [ServerSelectorX] Plugin ServerSelectorX v3.2.4 generated an exception while executing task 10057
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.WOODEN_SWORD
at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_131]
at org.bukkit.Material.valueOf(Material.java:1) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
at xyz.derkades.serverselectorx.SelectorMenu$1.run(SelectorMenu.java:200) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[01:01:33] [Server thread/WARN]: [ServerSelectorX] A sound with the name HORSE_ARMOR could not be found. Make sure that it is the right name for your server version.
[01:01:34] [Craft Scheduler Thread - 8/WARN]: [ServerSelectorX] Plugin ServerSelectorX v3.2.4 generated an exception while executing task 10072
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.WOODEN_SWORD
at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_131]
at org.bukkit.Material.valueOf(Material.java:1) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
at xyz.derkades.serverselectorx.SelectorMenu$1.run(SelectorMenu.java:200) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[01:01:34] [Server thread/WARN]: [ServerSelectorX] A sound with the name HORSE_ARMOR could not be found. Make sure that it is the right name for your server version.

`

Running it in a 1.12.2 spiggot.  Let me know what other info you might need and thank you.

**Comment by Derkades** [comment]
The default config contains an error, use WOOD_SWORD instead of WOODEN_SWORD
